### ISSUE TITLE
Usb- modul in ffki einbauen

### ISSUE THREAD

**Issue by rubo77** [fsteinel/gluon-packages#1]
Habe das hier versucht: https://github.com/rubo77/site-ffki/commit/1c229cf5c88008520a4bcab14685b997a88be2cc aber der build prozess bricht ab mit der Meldung "image too large" für den 841N, obwohl der ja gar keine USB Pakete bekommen soll... seltsam

**Comment by rubo77** [comment]
Vielleicht muss das auch noch in die `modules` rein, dass nur die Router mit 8MB auch dieses Repo abbekommen

**Comment by rubo77** [comment]
Ich habe es einmal probiert mit der korrekten `modules`: https://github.com/rubo77/site-ffki/blob/usb/modules

und mit einer modifizierten `targets/ar71xx-generic/profiles.mk` die jetzt einfach nur so aussieht:

```
$(eval $(call GluonProfile,TLWR842))
$(eval $(call GluonModel,TLWR842,tl-wr842n-v2,tp-link-tl-wr842n-nd-v2))

$(eval $(call GluonProfile,TLWR1043))
$(eval $(call GluonModel,TLWR1043,tl-wr1043nd-v2,tp-link-tl-wr1043n-nd-v2))
$(eval $(call GluonModel,TLWR1043,tl-wr1043nd-v3,tp-link-tl-wr1043n-nd-v3))

$(eval $(call GluonProfile,DIR505A1))
$(eval $(call GluonModel,DIR505A1,dir-505-a1,d-link-dir-505-rev-a1))
```

also enabled  nur ein paar 8MB Router, dann kommt die Fehlermeldung (too big) nicht, aber er findet dieses packages repo auch gar nicht:

```
Unknown package 'gluon-config-mode-usb-media'. 
Unknown package 'gluon-usb-media'. 
```

**Comment by rubo77** [comment]
Problem lag wahrscheinlich daran, dass ich kein 

```
make update
```

vorm erneuten bauen aufgerufen habe.

**Comment by rubo77** [comment]
Baut nicht:

```
make[4]: Entering directory '/media/workspace/gluon-build/gluon/packages/ffki/gluon-usb-media'
mkdir -p /media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2_gluon-ar71xx-generic/gluon-usb-media
cp -fpR ./src/* /media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2_gluon-ar71xx-generic/gluon-usb-media/
cp: cannot stat './src/*': No such file or directory
Makefile:33: recipe for target '/media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2_gluon-ar71xx-generic/gluon-usb-media/.prepared_7ed69c20696362b51e90e47ee09abd48' failed
make[4]: *** [/media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2_gluon-ar71xx-generic/gluon-usb-media/.prepared_7ed69c20696362b51e90e47ee09abd48] Error 1
make[4]: Leaving directory '/media/workspace/gluon-build/gluon/packages/ffki/gluon-usb-media'
package/Makefile:191: recipe for target 'package/feeds/ffki/gluon-usb-media/compile' failed
make[3]: *** [package/feeds/ffki/gluon-usb-media/compile] Error 2

```

**Comment by rubo77** [comment]
habe die cp src anweisung mal entfernt in meinem fork hier: https://github.com/rubo77/gluon-packages/commits/master

dann baut er weiter aber es kommt auch ein fehler, den ich nicht mehr erkennen kann: https://gist.github.com/rubo77/75134709dc99ded58e64

wo ist da überhaupt die Fehlermeldung versteckt?

**Comment by viisauksena** [comment]
vermutlich könntest du generell ein script einbauen das bei 
1. funktionierendem opkg strukturen 
2. den Routertyp checkt 
3. entsprechend (mit 8mb und usb) opkg update; opkg install usb_foo 
das skript selber wäre ja dann recht klein, und sollte mit dem first boot after sysupgrade laufen (vermutlich mit 1-2 minuten puffer)

soweit mein Vorschlag: also nicht nativ einbauen, aber nachladen

**Comment by viisauksena** [comment]
was mir gerade auffällt .. schon mit kleinsten adjustments bekomme ich für den 851v1-5 die gleiche Fehlermeldung .. der Rest baut super .. kann das also ein Relikt eines eigtl. anderen Fehlers sein?

**Comment by viisauksena** [comment]
das ja nicht so übersichtlich .. schreib doch zu deinem make mal am Ende dazu
`V=99 2>&1 | tee make_$(date +%y%m%d_%H%M).log`
dann kannste in der Datei nach **error:** oder die **warning** suchen

**Comment by rubo77** [comment]
Also miene gluon build Umgebung baut korrekt, wenn ich keine eigenen Module in meiner site.conf einbinde. erst sobald ich das selbstgebaute usb modul einbinde kommt der Fehler.

Eine sache fiel uns noch auf: das Modul  muss vor dem Modul  in der site.conf auftaucehn da dies von dem anderen abhängig ist (siehe https://github.com/rubo77/site-ffki/commit/a2ab9cfde7e4fdc31b6534e4a8e0ffe01ae62435 ) . jetzt baut er zwar etwas weiter aber bricht  mit diesem Fehler ab:

```
make[5]: Leaving directory '/media/workspace/gluon-build/gluon/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2_gluon-ar71xx-generic/gluon-usb-media'
Makefile:31: recipe for target '/media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2_gluon-ar71xx-generic/gluon-usb-media/.built' failed
make[4]: Leaving directory '/media/workspace/gluon-build/gluon/packages/ffki/gluon-usb-media'
package/Makefile:191: recipe for target 'package/feeds/ffki/gluon-usb-media/compile' failed
make[3]: Leaving directory '/media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt'
package/Makefile:188: recipe for target '/media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2_gluon-ar71xx-generic/stamp/.package_compile' failed
make[2]: Leaving directory '/media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt'
/media/workspace/gluon-build/gluon/Makefile:341: recipe for target 'prepare' failed
make[1]: Leaving directory '/media/workspace/gluon-build/gluon/build/ar71xx-generic/openwrt'
Makefile:72: recipe for target 'all' failed

```

Also ist der Fehler wohl: 

```
Makefile:31: recipe for target '.../gluon-usb-media/.built' failed
```

Was heisst denn "recipe for target "?

**Comment by fsteinel** [comment]
@viisauksena 
Ich glaub das liegt daran das ich die beiden Pakete von vorhanden (siehe Issue #2 ) abgeleitet habe...
Lese mich gerade ein wie OpenWRT aufgabut wird...

**Comment by fsteinel** [comment]
Weitere Tests jetzt mit `make V=s package/gluon-usb-media`...

**Comment by viisauksena** [comment]
du weisst schon das du eine Datei modules einbinden musst dort liegt `gluon/site/modules` und in etwa so aufgebaut sein muss ... 

```
GLUON_SITE_FEEDS='v14tov15helper ssidchanger banner treatment'
PACKAGES_V14TOV15HELPER_REPO=https://github.com/viisauksena/gluon-v14tov15-helper.git
PACKAGES_V14TOV15HELPER_COMMIT=74b423c678b1d548c6e0ae6d02af1481cac102a7
PACKAGES_V14TOV15HELPER_BRANCH=master
PACKAGES_SSIDCHANGER_REPO=https://github.com/viisauksena/gluon-ssid-changer.git
PACKAGES_SSIDCHANGER_COMMIT=fb6b87ec0b68fee73e3b029be73a5949becc9425
PACKAGES_SSIDCHANGER_BRANCH=chaos-calmer
PACKAGES_BANNER_REPO=https://github.com/viisauksena/gluon-banner.git
PACKAGES_BANNER_COMMIT=3beca95c8a3104db08909449788b17e01054bb7a
PACKAGES_BANNER_BRANCH=master
PACKAGES_TREATMENT_REPO=https://github.com/viisauksena/gluon-treatment.git
PACKAGES_TREATMENT_COMMIT=3e3fd75199ebe44a63e0c47c07e3354c72b63d41
PACKAGES_TREATMENT_BRANCH=master
```

dann kannst du in der site.mk dies einbinden 

```
...
        gluon-status-page \
        gluon-banner \
        haveged \
        iptables \
        wpa-supplicant-mini \
        gluon-ssid-changer \
...
```

(alles live beispiele aus Freiburg .. hier gluon-ssid-changer und gluon-banner eingebaut (=Namen aus den git repo))
und natürlich muss da jeweils ein passendes Makefile in dem git repo liegen .. "notfalls" könntest du zum Beispiel eines der repos hier kopieren .. und komplett für deine Zwecke umbenennen und anpassen (inkl dem generischen Makefile)

**Comment by rubo77** [comment]
Natürlich wissen wir das mit der modules datei. Wenn du den links in meinen vorigen posts gefolgt wärest hättest du gesehen, wie wir das angegangen sind.

Hier ist das site repo die wir benutzt haben: https://github.com/rubo77/site-ffki/tree/usb
also der branch "usb"

**Comment by viisauksena** [comment]
ja, ich wollt nur die basics sicher haben .. ok, wenn die modules in dem branch korrekt ist liegt dort der Fehler (daher auch die refferenz impl.) 
da steht noch branch=my_branch .. das muss master heissen wenn kein anderer gewählt wurde.
und ich vermute das es nicht möglich ist 2 Pakete gleichzeitig auf diese Weise einzubinden, vermute da müsste noch ein Makefile dahin ... 

vielleicht ists aber auch "nur" der branch, <del>der commit ist da natürlich aber auch schon ein älterer, zumindest nicht der letzte</del>(mein irrtum zum aktuellsten commit)

sonst : versuche doch die modules mal klar zu machen (dann finden sich fehler auch leichter) und versuche doch mal je Paket ein git repo zu haben (also nicht packages .. sonder die unterverzeichnisse direkt als eigenständige repo einzubinden in die modules.
wie gesagt das oben ist der in freiburg funktionierende Teil 

die modules sorgt ja nur dafür das die Dinge mit gebaut werden, eingebaut werden die dann wenn das in der site.mk auch vorgesehen werden, das von euch beschriebene Problem ist ja das das erst garnicht baut.

**Comment by rubo77** [comment]
Mir sieht's so aus, als ob die Module schon richtig eingebunden sind und ich schätze eher dass da ein Fehler in unseren Makefile's ist. Bin da noch kein Experte

**Comment by viisauksena** [comment]
hast du das nun mit dem branch angeben versucht und evtl auch bei den https zu belassen ?
bei mir funktioniert dies hier, aber da liegen die pakete einzeln .. könnte mir daher vorstellen das das makefile in deiner refferenz falsch ist (wo ich ja nichtmal sicher bin ob das so funktioniert wie du das gebaut hast - ohne branch mit git angabe)

```
GLUON_SITE_FEEDS='v14tov15helper ssidchanger banner treatment'
# kann man dann als          gluon-treatment         in site.mk einbinden
PACKAGES_TREATMENT_REPO=https://github.com/viisauksena/gluon-treatment.git
PACKAGES_TREATMENT_COMMIT=3e3fd75199ebe44a63e0c47c07e3354c72b63d41
PACKAGES_TREATMENT_BRANCH=master
# ... und dann kommen die anderen v14tov15helper ssidchanger banner
# ... man muss die ja nicht in site.mk einbinden
```

**Comment by rubo77** [comment]
Ich habe mal `PACKAGES_FFKI_BRANCH=master` in der modules ergänzt...

Aber selber Fehler (es scheint master ist eh der default)

**Comment by rubo77** [comment]
@Tarnatos meint, vielleicht darf man diese Abhängigkeit nicht in das Makefile reinschreiben:

```
DEPENDS:=gluon-config-mode-core-virtual
```

(das paket ist ev. gar nicht drin)

**Comment by rubo77** [comment]
Ich habe das jetzt noch mal ohne das `-virtual` paket ausprobiert, also nur `gluon-config-mode-core` und dann diese module unten für die Router, die USB haben mit reingenommen:
https://github.com/rubo77/site-ffki/blob/usb/site.mk#L70

bekomme beim compilieren nun den abbruch:

```
package/Makefile:191: recipe for target 'package/feeds/ffki/gluon-usb-media/compile' failed
```

**Comment by rubo77** [comment]
musste doch mit `-virtual` dort waren diverse Fehler drin.

ist alles korrigiert in https://github.com/rubo77/gluon-packages

(Siehe commit history dort)
